// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  用于向前端返回计数器数据
	 * 
	 *  @param count 输入的数字
	 */
	greet: (count: number) => __TAURI_INVOKE<string>("greet", { count }),
};

